set -sa terminal-overrides ",xterm-ghostty:Tc"
set -sa terminal-overrides ",xterm-256color:Tc"
set -ag terminal-features ",xterm-256color:RGB"
set -ag terminal-features ",xterm-ghostty:RGB"
set-environment -g COLORTERM truecolor
set-environment -g CLAUDE_CODE_TMUX_TRUECOLOR 1
