FROM archlinux:base

# Pacman's package sandbox is incompatible with amd64 emulation in some Docker
# runtimes. This image is disposable, and --disable-sandbox works natively too.
RUN pacman --disable-sandbox -Syu --noconfirm --needed \
    bat \
    ca-certificates \
    curl \
    fd \
    fish \
    fzf \
    git \
    python-pip \
    ripgrep \
    tmux \
    vim \
    zoxide \
    zsh

RUN useradd -m -s /bin/bash testuser

USER testuser
WORKDIR /home/testuser

ARG CHEZMOI_INSTALLER_CACHE_BUST=manual-build
RUN test -n "$CHEZMOI_INSTALLER_CACHE_BUST" && \
    curl --proto '=https' --tlsv1.2 -fsSL \
        -o /tmp/get-chezmoi.sh https://get.chezmoi.io && \
    sh /tmp/get-chezmoi.sh -b /home/testuser/.local/bin && \
    rm -f /tmp/get-chezmoi.sh

RUN python3 -m pip install --user --break-system-packages \
    'xonsh[ptk]' \
    'catppuccin[pygments]'

ENV PATH="/home/testuser/.local/bin:/home/testuser/bin:${PATH}"

CMD ["/bin/bash"]
